version: "2"
services:
  web:
    image: nicola24/proxy
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
  redis:
    image: redis:latest
    ports:
        - "6379:6379"
